### PR TITLE
Changed TChangeEvent and TUndoList to public instead of protected

### PR DESCRIPTION
**Pull request by laconical77**
These need to be public or C++ Builder complains that they are not accessible.

### CODE REVIEW

**Comment by NilsHoyer** [comment]
I still don't understand, when a declaration has to be public, protected or outside a class definition for C++Builder. But I would like to understand this. So I wish to have a small demo program, I can compile completely, to reproduce the problems on my end. But I don't have the knowledge of C++Builder to write an entiered application...

**Comment by laconical77** [comment]
You don't actually need to write any C++ code at all. After generating the C++ headers, bpl and bpi files, all I did was create an empty C++ application and added the TBCEditor component to the main form. I then tried to compile it and started getting compilation errors immediately. Not a single line of code required. This is using Berlin - I don't know if the same problems exist in earlier versions of RAD Studio. What version are you using for development?

**Comment by NilsHoyer** [comment]
> You don't actually need to write any C++ code at all.

I don't want this. But I can to be able to check my Delphi Modifications 
for C++ without bothering you with bad changes.

Additional, I think it would be great for other C++Builder developers to 
have a small demo program for their first steps.

> What version are you using for development?

I'm using Delphi XE4. I don't want to update, to make sure the BCEditor 
will works with this ("old") Delphi version too.
