### ISSUE TITLE
Cannot build in 10.2 Update 1

### ISSUE THREAD

**Issue by AlbertWiersch** [bonecode/BCEditor#43]
I get these dcc32 errors:
[dcc32 Error] BCEditor.pas(6862): E2010 Incompatible types: 'System.TArray<System.Byte>' and 'Pointer'
[dcc32 Error] BCEditor.pas(7100): E2010 Incompatible types: 'System.TArray<System.Byte>' and 'Pointer'

For this line:
          FHookedCommandHandlers[LIndex].Proc(Self, True, Ord(ACommand), @AData[0], Length(AData),
            LHandledLong, FHookedCommandHandlers[LIndex].HandlerData);

And this line:
          FHookedCommandHandlers[LIndex].Proc(Self, False, Ord(ACommand), @AData[0], Length(AData),
            LHandledLong, FHookedCommandHandlers[LIndex].HandlerData);

**Comment by civilian7** [comment]
change @adata[0] to adata

**Comment by AlbertWiersch** [comment]
Thanks... that compiled.

**Comment by NilsHoyer** [comment]
I've fixed this bug for the next commit.
